# Generated by Django 4.2.16 on 2024-10-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='musicas',
            new_name='filmes',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='artista',
        ),
    ]
